# Generated by Django 4.2.3 on 2023-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('job_description', models.TextField(max_length=5000)),
                ('job_requirements', models.TextField(blank=True, max_length=5000)),
                ('salary_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_mode', models.CharField(max_length=100)),
                ('required_driving_categories', models.CharField(choices=[('Permanent', 'Na stałe'), ('Contract', 'Zlecenie')], max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('contract_duration', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('BE', 'BE'), ('C1', 'C1'), ('C1E', 'C1E'), ('C', 'C'), ('CE', 'CE'), ('D1', 'D1'), ('D1E', 'D1E'), ('D', 'D'), ('DE', 'DE')], max_length=20)),
            ],
        ),
    ]
